import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
    // Mens Data

    {
        _id: uuid(),
        title: "Men's T-Shirt",
        description: "A comfortable and stylish t-shirt for men",
        price: 799,
        origianlPrice: 1499,
        percentage: 47,
        brand: "XYZ Brand",
        size: "M",
        rating: 4.5,
        image: "https://res.cloudinary.com/dwegb6a4s/image/upload/v1690186785/e-commerce/Men/Men_s_tshirt_pvpfvr.jpg",
        category: "men",
        reviews: "2.9k",
        instock: true,
    },
    {
        _id: uuid(),
        title: "Men's Hoodie",
        description: "A warm and cozy hoodie for men",
        price: 1199,
        origianlPrice: 1799,
        percentage: 33,
        brand: "ABC Brand",
        size: "L",
        rating: 3.2,
        image: "https://res.cloudinary.com/dwegb6a4s/image/upload/v1690186784/e-commerce/Men/Men_s_Hoodie_c9tgwy.jpg",
        category: "men",
        reviews: "1.5k",
        instock: true,
    },
    {
        _id: uuid(),
        title: "Men's Jeans",
        description: "Classic denim jeans for men",
        price: 1099,
        origianlPrice: 1399,
        percentage: 21,
        brand: "XYZ Brand",
        size: "L",
        rating: 4.8,
        image: "https://res.cloudinary.com/dwegb6a4s/image/upload/v1690186784/e-commerce/Men/Men_s_Jeans_gsynuf.jpg",
        category: "men",
        reviews: "1.9k",
        instock: true,
    },
    {
        _id: uuid(),
        title: "Men's Polo Shirt",
        description: "A stylish polo shirt for men",
        price: 799,
        origianlPrice: 1499,
        percentage: 47,
        brand: "ABC Brand",
        size: "S",
        rating: 3.6,
        image: "https://res.cloudinary.com/dwegb6a4s/image/upload/v1690186784/e-commerce/Men/Men_s_polo_shirt_p3pvbw.jpg",
        category: "men",
        reviews: "2.5k",
        instock: true,
    },
    {
        _id: uuid(),
        title: "Men's Dress Shirt",
        description: "A formal dress shirt for men",
        price: 649,
        origianlPrice: 999,
        percentage: 35,
        brand: "XYZ Brand",
        size: "XL",
        rating: 2.3,
        image: "https://res.cloudinary.com/dwegb6a4s/image/upload/v1690186784/e-commerce/Men/Men_s_dress_shirt_uoyut1.jpg",
        category: "men",
        reviews: "1.9k",
        instock: true,
    },
    {
        _id: uuid(),
        title: "Men's Shorts",
        description: "Casual and comfortable shorts for men",
        price: 599,
        origianlPrice: 799,
        percentage: 25,
        brand: "ABC Brand",
        size: "M",
        rating: 2.7,
        image: "https://res.cloudinary.com/dwegb6a4s/image/upload/v1690186785/e-commerce/Men/Men_s_shorts_si4u7w.jpg",
        category: "men",
        reviews: "1.6k",
        instock: true,
    },
    {
        _id: uuid(),
        title: "Men's Blazer",
        description: "A stylish blazer for men",
        price: 1099,
        origianlPrice: 1399,
        percentage: 21,
        brand: "XYZ Brand",
        size: "XXL",
        rating: 3.1,
        image: "https://res.cloudinary.com/dwegb6a4s/image/upload/v1690194672/e-commerce/New%20Men/Men_s_blazer_ttvffp.jpg",
        category: "men",
        reviews: "1.8k",
        instock: true,
    },
    {
        _id: uuid(),
        title: "Men's Sweatpants",
        description: "Comfortable sweatpants for men",
        price: 849,
        origianlPrice: 1299,
        percentage: 35,
        brand: "ABC Brand",
        size: "XL",
        rating: 4.4,
        image: "https://res.cloudinary.com/dwegb6a4s/image/upload/v1690186785/e-commerce/Men/Men_s_sweatpants_rxpo9l.jpg",
        category: "men",
        reviews: "1.2k",
        instock: true,
    },
    {
        _id: uuid(),
        title: "Men's Winter Jacket",
        description: "A warm winter jacket for men",
        price: 1199,
        origianlPrice: 1799,
        percentage: 33,
        brand: "XYZ Brand",
        size: "L",
        rating: 3.9,
        image: "https://res.cloudinary.com/dwegb6a4s/image/upload/v1690186785/e-commerce/Men/Men_s_winter_jacket_hynmyt.jpg",
        category: "men",
        reviews: "1.3k",
        instock: true,
    },
    {
        _id: uuid(),
        title: "Men's Socks",
        description: "Comfortable and breathable socks for men",
        price: 599,
        origianlPrice: 899,
        percentage: 33,
        brand: "ABC Brand",
        size: "M",
        rating: 2.0,
        image: "https://res.cloudinary.com/dwegb6a4s/image/upload/v1690186785/e-commerce/Men/Men_s_socks_vk37gk.jpg",
        category: "men",
        reviews: "1.5k",
        instock: true,
    },

    // Women's data

    {
        _id: uuid(),
        title: "Women's Dress",
        description: "A beautiful and elegant dress for women",
        price: 1199,
        origianlPrice: 1799,
        percentage: 33,
        brand: "XYZ Brand",
        size: "M",
        rating: 4.5,
        image: "https://res.cloudinary.com/dwegb6a4s/image/upload/v1690187796/e-commerce/Women/Women_s_dress_2_xntp5e.jpg",
        category: "women",
        reviews: "1.6k",
        instock: true,
    },
    {
        _id: uuid(),
        title: "Women's Dress",
        description:
            "Elegant women's dress: Timeless style, flattering fit, ultimate sophistication",
        price: 1199,
        origianlPrice: 2099,
        percentage: 43,
        brand: "ABC Brand",
        size: "XL",
        rating: 3.2,
        image: "https://res.cloudinary.com/dwegb6a4s/image/upload/v1690187796/e-commerce/Women/Women_s_dress_3_xbvdih.jpg",
        category: "women",
        reviews: "1.7k",
        instock: true,
    },
    {
        _id: uuid(),
        title: "Women's Jeans",
        description: "Trendy denim jeans for women",
        price: 899,
        origianlPrice: 1299,
        percentage: 31,
        brand: "XYZ Brand",
        size: "L",
        rating: 4.8,
        image: "https://res.cloudinary.com/dwegb6a4s/image/upload/v1690187797/e-commerce/Women/Women_s_Jeans_fqntbn.jpg",
        category: "women",
        reviews: "2.7k",
        instock: true,
    },
    {
        _id: uuid(),
        title: "Women's Dress",
        description:
            "Chic women's dress: Effortless grace, versatile, fashion-forward must-have.",
        price: 799,
        origianlPrice: 1499,
        percentage: 47,
        brand: "ABC Brand",
        size: "S",
        rating: 3.6,
        image: "https://res.cloudinary.com/dwegb6a4s/image/upload/v1690187795/e-commerce/Women/Women_s_dress_4_iep0pg.jpg",
        category: "women",
        reviews: "1.7k",
        instock: true,
    },
    {
        _id: uuid(),
        title: "Women's Skirt",
        description: "A stylish skirt for women",
        price: 699,
        origianlPrice: 999,
        percentage: 30,
        brand: "XYZ Brand",
        size: "S",
        rating: 4.3,
        image: "https://res.cloudinary.com/dwegb6a4s/image/upload/v1690187797/e-commerce/Women/Women_s_Skirt_xzpbyw.jpg",
        category: "women",
        reviews: "2.7k",
        instock: true,
    },
    {
        _id: uuid(),
        title: "Women's Dress",
        description:
            "Feminine dress: Graceful silhouette, radiant colors, confident charm.",
        price: 1399,
        origianlPrice: 1999,
        percentage: 30,
        brand: "ABC Brand",
        size: "XL",
        rating: 2.7,
        image: "https://res.cloudinary.com/dwegb6a4s/image/upload/v1690187795/e-commerce/Women/Women_s_dress_5_pgr8y9.jpg",
        category: "women",
        reviews: "6.7k",
        instock: true,
    },
    {
        _id: uuid(),
        title: "Women's Dress",
        description:
            "Stunning women's dress: Alluring design, impeccable craftsmanship, pure elegance.",
        price: 1399,
        origianlPrice: 1999,
        percentage: 30,
        brand: "XYZ Brand",
        size: "M",
        rating: 4.1,
        image: "https://res.cloudinary.com/dwegb6a4s/image/upload/v1690187795/e-commerce/Women/Women_s_dress_6_pq210b.jpg",
        category: "women",
        reviews: "4.7k",
        instock: true,
    },
    {
        _id: uuid(),
        title: "Women's Leggings",
        description: "Comfortable leggings for women",
        price: 799,
        origianlPrice: 1099,
        percentage: 27,
        brand: "ABC Brand",
        size: "L",
        rating: 2.4,
        image: "https://res.cloudinary.com/dwegb6a4s/image/upload/v1690187797/e-commerce/Women/Women_s_Leggings_yy6lsp.jpg",
        category: "women",
        reviews: "20.7k",
        instock: true,
    },
    {
        _id: uuid(),
        title: "Women's Jumpsuit",
        description: "A trendy jumpsuit for women",
        price: 1199,
        origianlPrice: 1799,
        percentage: 33,
        brand: "XYZ Brand",
        size: "XL",
        rating: 2.9,
        image: "https://res.cloudinary.com/dwegb6a4s/image/upload/v1690187797/e-commerce/Women/Women_s_JumpSuit_wc639z.jpg",
        category: "women",
        reviews: "2.7k",
        instock: true,
    },
    {
        _id: uuid(),
        title: "Women's Dress",
        description:
            "Exquisite women's dress: Timeless beauty, luxurious fabric, captivating allure.",
        price: 649,
        origianlPrice: 999,
        percentage: 35,
        brand: "ABC Brand",
        size: "S",
        rating: 4.0,
        image: "https://res.cloudinary.com/dwegb6a4s/image/upload/v1690187795/e-commerce/Women/Women_s_dress_7_u1nlaf.jpg",
        category: "women",
        reviews: "10.7k",
        instock: true,
    },

    // Kids data

    {
        _id: uuid(),
        title: "Kids' T-Shirt",
        description: "A comfortable t-shirt for kids",
        price: 299,
        origianlPrice: 499,
        percentage: 40,
        brand: "XYZ Kids",
        size: "M",
        rating: 4.5,
        image: "https://res.cloudinary.com/dwegb6a4s/image/upload/v1690188125/e-commerce/Kids/Kids_s_tshirt_pant_ofyhct.jpg",
        category: "kids",
        reviews: "8.3k",
        instock: true,
    },

    {
        _id: uuid(),
        title: "Kids' Dress",
        description: "An elegant dress for girls",
        price: 599,
        origianlPrice: 899,
        percentage: 33,
        brand: "Fashion Kids",
        size: "L",
        rating: 3.2,
        image: "https://res.cloudinary.com/dwegb6a4s/image/upload/v1690188125/e-commerce/Kids/Kids_s_dress_r3ebyj.jpg",
        category: "kids",
        reviews: "6.5k",
        instock: true,
    },
    {
        _id: uuid(),
        title: "Boys' Denim Jeans",
        description: "Stylish denim jeans for boys",
        price: 499,
        origianlPrice: 799,
        percentage: 38,
        brand: "Cool Kids",
        size: "S",
        rating: 2.7,
        image: "https://res.cloudinary.com/dwegb6a4s/image/upload/v1690188125/e-commerce/Kids/Kids_s_tshirt_pant_2_lplgkl.jpg",
        category: "kids",
        reviews: "4.9k",
        instock: true,
    },
    {
        _id: uuid(),
        title: "Girls' Summer Dress",
        description: "Light and trendy summer dress for girls",
        price: 399,
        origianlPrice: 599,
        percentage: 33,
        brand: "Sweetie Pies",
        size: "M",
        rating: 2.8,
        image: "https://res.cloudinary.com/dwegb6a4s/image/upload/v1690188124/e-commerce/Kids/Kids_s_tshirt_pant_1_q56gc3.jpg",
        category: "kids",
        reviews: "7.1k",
        instock: true,
    },
    {
        _id: uuid(),
        title: "Boys' Polo Shirt",
        description: "Classic polo shirt for boys",
        price: 249,
        origianlPrice: 399,
        percentage: 38,
        brand: "Cool Kids",
        size: "L",
        rating: 4.3,
        image: "https://res.cloudinary.com/dwegb6a4s/image/upload/v1690188126/e-commerce/Kids/Kids_s_tshirt_pant_3_wm1xvu.jpg",
        category: "kids",
        reviews: "3.2k",
        instock: true,
    },
    {
        _id: uuid(),
        title: "Kids' Shoes",
        description: "Comfy and stylish Shoes for kids",
        price: 399,
        origianlPrice: 699,
        percentage: 43,
        brand: "Kicks and Run",
        size: "M",
        rating: 2.6,
        image: "https://res.cloudinary.com/dwegb6a4s/image/upload/v1690188126/e-commerce/Kids/Kids_s_Shoes_ljruqd.png",
        category: "kids",
        reviews: "5.5k",
        instock: true,
    },
    {
        _id: uuid(),
        title: "Boy's Watch",
        description: "Pretty cool watch for kids",
        price: 349,
        origianlPrice: 499,
        percentage: 30,
        brand: "Fashion Kids",
        size: "S",
        rating: 4.4,
        image: "https://res.cloudinary.com/dwegb6a4s/image/upload/v1690188126/e-commerce/Kids/Kids_s_watch_ijtwg0.jpg",
        category: "kids",
        reviews: "2.8k",
        instock: true,
    },
    {
        _id: uuid(),
        title: "Girl's Watch",
        description: "Pretty cool watch for kids",
        price: 199,
        origianlPrice: 299,
        percentage: 33,
        brand: "XYZ Kids",
        size: "L",
        rating: 3.1,
        image: "https://res.cloudinary.com/dwegb6a4s/image/upload/v1690188125/e-commerce/Kids/Kids_s_watch_1_oslgzd.jpg",
        category: "kids",
        reviews: "3.9k",
        instock: true,
    },
    {
        _id: uuid(),
        title: "Kid's t-shirt and Pant",
        description: "Gorgeous party dress for girls",
        price: 699,
        origianlPrice: 1099,
        percentage: 36,
        brand: "Sweetie Pies",
        size: "M",
        rating: 4.9,
        image: "https://res.cloudinary.com/dwegb6a4s/image/upload/v1690188125/e-commerce/Kids/Kids_s_tshirt_pant_4_zdwrph.jpg",
        category: "kids",
        reviews: "9.2k",
        instock: true,
    },
    {
        _id: uuid(),
        title: "Kids' Sandles",
        description: "Warm and stylish hooded jacket for kids",
        price: 599,
        origianlPrice: 899,
        percentage: 33,
        brand: "Kicks and Run",
        size: "L",
        rating: 3.7,
        image: "https://res.cloudinary.com/dwegb6a4s/image/upload/v1690188125/e-commerce/Kids/Kids_s_Sandles_fjnuc5.jpg",
        category: "kids",
        reviews: "6.4k",
        instock: true,
    },

    // Electronics data

    // {
    //     _id: uuid(),
    //     title: "Smartphone",
    //     description: "A powerful smartphone with advanced features",
    //     price: 699,
    //     origianlPrice: 50,
    //     percentage: 60,
    //     brand: "XYZ Brand",
    //     size: ["128GB", "256GB", "512GB"],
    //     rating: 3.5,
    //     image: "https://example.com/images/smartphone.jpg",
    //     category: "Electronics",
    //     reviews: "2.7k",
    // },
    // {
    //     _id: uuid(),
    //     title: "Laptop",
    //     description: "A high-performance laptop for work and gaming",
    //     price: 1299,
    //     origianlPrice: 50,
    //     percentage: 60,
    //     brand: "ABC Brand",
    //     size: ["13-inch", "15-inch", "17-inch"],
    //     rating: 4.2,
    //     image: "https://example.com/images/laptop.jpg",
    //     category: "Electronics",
    //     reviews: "2.1k",
    // },
    // {
    //     _id: uuid(),
    //     title: "Headphones",
    //     description: "Wireless headphones with noise cancellation",
    //     price: 199,
    //     origianlPrice: 50,
    //     percentage: 60,
    //     brand: "XYZ Brand",
    //     size: ["One Size"],
    //     rating: 3.8,
    //     image: "https://example.com/images/headphones.jpg",
    //     category: "Electronics",
    //     reviews: "1.4k",
    // },
    // {
    //     _id: uuid(),
    //     title: "Smart TV",
    //     description: "A high-resolution smart TV with built-in apps",
    //     price: 899,
    //     origianlPrice: 50,
    //     percentage: 60,
    //     brand: "ABC Brand",
    //     size: ["55-inch", "65-inch", "75-inch"],
    //     rating: 4.6,
    //     image: "https://example.com/images/smart-tv.jpg",
    //     category: "Electronics",
    //     reviews: "2.1k",
    // },
    // {
    //     _id: uuid(),
    //     title: "Smartwatch",
    //     description: "A feature-rich smartwatch with health tracking",
    //     price: 299,
    //     origianlPrice: 50,
    //     percentage: 60,
    //     brand: "XYZ Brand",
    //     size: ["One Size"],
    //     rating: 2.3,
    //     image: "https://example.com/images/smartwatch.jpg",
    //     category: "Electronics",
    //     reviews: "2.5k",
    // },
    // {
    //     _id: uuid(),
    //     title: "Camera",
    //     description: "A professional-grade camera for photography enthusiasts",
    //     price: 1499,
    //     origianlPrice: 50,
    //     percentage: 60,
    //     brand: "ABC Brand",
    //     size: ["One Size"],
    //     rating: 4.7,
    //     image: "https://example.com/images/camera.jpg",
    //     category: "Electronics",
    //     reviews: "2.7k",
    // },
    // {
    //     _id: uuid(),
    //     title: "Tablet",
    //     description: "A versatile tablet for work and entertainment",
    //     price: 499,
    //     origianlPrice: 50,
    //     percentage: 60,
    //     brand: "XYZ Brand",
    //     size: ["10-inch", "12-inch"],
    //     rating: 2.1,
    //     image: "https://example.com/images/tablet.jpg",
    //     category: "Electronics",
    //     reviews: "1.4k",
    // },
    // {
    //     _id: uuid(),
    //     title: "Gaming Console",
    //     description: "A gaming console for immersive gaming experiences",
    //     price: 399,
    //     origianlPrice: 50,
    //     percentage: 60,
    //     brand: "ABC Brand",
    //     size: ["One Size"],
    //     rating: 4.4,
    //     image: "https://example.com/images/gaming-console.jpg",
    //     category: "Electronics",
    //     reviews: "1.3k",
    // },
    // {
    //     _id: uuid(),
    //     title: "Wireless Speaker",
    //     description: "A portable wireless speaker for music on the go",
    //     price: 79,
    //     origianlPrice: 50,
    //     percentage: 60,
    //     brand: "XYZ Brand",
    //     size: ["One Size"],
    //     rating: 3.9,
    //     image: "https://example.com/images/wireless-speaker.jpg",
    //     category: "Electronics",
    //     reviews: "1.6k",
    // },
    // {
    //     _id: uuid(),
    //     title: "External Hard Drive",
    //     description: "A reliable external hard drive for data storage",
    //     price: 129,
    //     origianlPrice: 50,
    //     percentage: 60,
    //     brand: "ABC Brand",
    //     size: ["1TB", "2TB", "4TB"],
    //     rating: 4.0,
    //     image: "https://example.com/images/external-hard-drive.jpg",
    //     category: "Electronics",
    //     reviews: "1.8k",
    // },
];

// ["S", "M", "L", "XL", "XXL"]
