const array = [
    {
        _id: uuid(),
        title: "Smartphone",
        description: "A powerful smartphone with advanced features",
        price: 699.99,
        brand: "XYZ Brand",
        size: ["128GB", "256GB", "512GB"],
        rating: 4.5,
        image: "https://example.com/images/smartphone.jpg",
        category: "Electronics",
    },
    {
        _id: uuid(),
        title: "Laptop",
        description: "A high-performance laptop for work and gaming",
        price: 1299.99,
        brand: "ABC Brand",
        size: ["13-inch", "15-inch", "17-inch"],
        rating: 4.2,
        image: "https://example.com/images/laptop.jpg",
        category: "Electronics",
    },
    {
        _id: uuid(),
        title: "Headphones",
        description: "Wireless headphones with noise cancellation",
        price: 199.99,
        brand: "XYZ Brand",
        size: ["One Size"],
        rating: 4.8,
        image: "https://example.com/images/headphones.jpg",
        category: "Electronics",
    },
    {
        _id: uuid(),
        title: "Smart TV",
        description: "A high-resolution smart TV with built-in apps",
        price: 899.99,
        brand: "ABC Brand",
        size: ["55-inch", "65-inch", "75-inch"],
        rating: 4.6,
        image: "https://example.com/images/smart-tv.jpg",
        category: "Electronics",
    },
    {
        _id: uuid(),
        title: "Smartwatch",
        description: "A feature-rich smartwatch with health tracking",
        price: 299.99,
        brand: "XYZ Brand",
        size: ["One Size"],
        rating: 4.3,
        image: "https://example.com/images/smartwatch.jpg",
        category: "Electronics",
    },
    {
        _id: uuid(),
        title: "Camera",
        description: "A professional-grade camera for photography enthusiasts",
        price: 1499.99,
        brand: "ABC Brand",
        size: ["One Size"],
        rating: 4.7,
        image: "https://example.com/images/camera.jpg",
        category: "Electronics",
    },
    {
        _id: uuid(),
        title: "Tablet",
        description: "A versatile tablet for work and entertainment",
        price: 499.99,
        brand: "XYZ Brand",
        size: ["10-inch", "12-inch"],
        rating: 4.1,
        image: "https://example.com/images/tablet.jpg",
        category: "Electronics",
    },
    {
        _id: uuid(),
        title: "Gaming Console",
        description: "A gaming console for immersive gaming experiences",
        price: 399.99,
        brand: "ABC Brand",
        size: ["One Size"],
        rating: 4.4,
        image: "https://example.com/images/gaming-console.jpg",
        category: "Electronics",
    },
    {
        _id: uuid(),
        title: "Wireless Speaker",
        description: "A portable wireless speaker for music on the go",
        price: 79.99,
        brand: "XYZ Brand",
        size: ["One Size"],
        rating: 4.9,
        image: "https://example.com/images/wireless-speaker.jpg",
        category: "Electronics",
    },
    {
        _id: uuid(),
        title: "External Hard Drive",
        description: "A reliable external hard drive for data storage",
        price: 129.99,
        brand: "ABC Brand",
        size: ["1TB", "2TB", "4TB"],
        rating: 4.0,
        image: "https://example.com/images/external-hard-drive.jpg",
        category: "Electronics",
    },
];
